var OA_output = new Array(); 
OA_output['1196'] = '';
OA_output['1196'] += "<"+"script type=\'text/javascript\'>\n";
OA_output['1196'] += "<"+"!--//<"+"![CDATA[\n";
OA_output['1196'] += "document.MAX_ct0 =\'\';\n";
OA_output['1196'] += "var m3_u = (location.protocol==\'https:\'?\'https://cas.criteo.com/delivery/ajs.php?\':\'http://cas.criteo.com/delivery/ajs.php?\');\n";
OA_output['1196'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['1196'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['1196'] += "document.write (\"zoneid=172642\");document.write(\"&amp;nodis=1\");\n";
OA_output['1196'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['1196'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['1196'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['1196'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['1196'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['1196'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['1196'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['1196'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['1196'] += "}\n";
OA_output['1196'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['1196'] += "document.write (\"\'><"+"/scr\"+\"ipt>\");\n";
OA_output['1196'] += "//]]>--><"+"/script><"+"div id=\'beacon_2019a255eb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=1208&amp;campaignid=196&amp;zoneid=1196&amp;loc=1&amp;referer=http%3A%2F%2Fwww.pro-football-reference.com%2Fyears%2F2015%2F&amp;cb=2019a255eb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['1197'] = '';
OA_output['1197'] += "<"+"div class=\"adiply_ad_holder\" style=\"width:160px;height:600px;margin:0;padding:0\">\n";
OA_output['1197'] += "<"+"/div>\n";
OA_output['1197'] += "<"+"script type=\"text/javascript\">\n";
OA_output['1197'] += "var adiply_divs = document.getElementsByClassName(\"adiply_ad_holder\");\n";
OA_output['1197'] += "var adiply_final_div_id = \"adiply_ad_holder_\" + Math.floor((Math.random() * 100000) + 1);\n";
OA_output['1197'] += "for(var i=0;i<"+"adiply_divs.length; i++){\n";
OA_output['1197'] += "if(adiply_divs[i].id) continue;\n";
OA_output['1197'] += "adiply_divs[i].setAttribute(\"id\", adiply_final_div_id);\n";
OA_output['1197'] += "break;\n";
OA_output['1197'] += "}\n";
OA_output['1197'] += "var OX_ads = OX_ads || [];\n";
OA_output['1197'] += "OX_ads.push({\n";
OA_output['1197'] += "slot_id: adiply_final_div_id,\n";
OA_output['1197'] += "auid: \"537209672\"\n";
OA_output['1197'] += "});\n";
OA_output['1197'] += "<"+"/script>\n";
OA_output['1197'] += "<"+"script type=\"text/javascript\" src=\"http://us-ads.openx.net/w/1.0/jstag\"><"+"/script><"+"div id=\'beacon_cb694aa18d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=1209&amp;campaignid=196&amp;zoneid=1197&amp;loc=1&amp;referer=http%3A%2F%2Fwww.pro-football-reference.com%2Fyears%2F2015%2F&amp;cb=cb694aa18d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['1198'] = '';
OA_output['1198'] += "<"+"script type=\'text/javascript\'>\n";
OA_output['1198'] += "<"+"!--//<"+"![CDATA[\n";
OA_output['1198'] += "document.MAX_ct0 =\'\';\n";
OA_output['1198'] += "var m3_u = (location.protocol==\'https:\'?\'https://cas.criteo.com/delivery/ajs.php?\':\'http://cas.criteo.com/delivery/ajs.php?\');\n";
OA_output['1198'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['1198'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['1198'] += "document.write (\"zoneid=172620\");document.write(\"&amp;nodis=1\");\n";
OA_output['1198'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['1198'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['1198'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['1198'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['1198'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['1198'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['1198'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['1198'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['1198'] += "}\n";
OA_output['1198'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['1198'] += "document.write (\"\'><"+"/scr\"+\"ipt>\");\n";
OA_output['1198'] += "//]]>--><"+"/script><"+"div id=\'beacon_2306d8b94e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=1210&amp;campaignid=196&amp;zoneid=1198&amp;loc=1&amp;referer=http%3A%2F%2Fwww.pro-football-reference.com%2Fyears%2F2015%2F&amp;cb=2306d8b94e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['1199'] = '';
OA_output['1199'] += "<"+"script type=\'text/javascript\'>\n";
OA_output['1199'] += "<"+"!--//<"+"![CDATA[\n";
OA_output['1199'] += "document.MAX_ct0 =\'\';\n";
OA_output['1199'] += "var m3_u = (location.protocol==\'https:\'?\'https://cas.criteo.com/delivery/ajs.php?\':\'http://cas.criteo.com/delivery/ajs.php?\');\n";
OA_output['1199'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['1199'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['1199'] += "document.write (\"zoneid=172646\");document.write(\"&amp;nodis=1\");\n";
OA_output['1199'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['1199'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['1199'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['1199'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['1199'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['1199'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['1199'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['1199'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['1199'] += "}\n";
OA_output['1199'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['1199'] += "document.write (\"\'><"+"/scr\"+\"ipt>\");\n";
OA_output['1199'] += "//]]>--><"+"/script><"+"div id=\'beacon_88677fe121\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=1211&amp;campaignid=196&amp;zoneid=1199&amp;loc=1&amp;referer=http%3A%2F%2Fwww.pro-football-reference.com%2Fyears%2F2015%2F&amp;cb=88677fe121\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['1200'] = '';
OA_output['1200'] += "<"+"div id=\'beacon_f3a1840089\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=1212&amp;campaignid=196&amp;zoneid=1200&amp;loc=1&amp;referer=http%3A%2F%2Fwww.pro-football-reference.com%2Fyears%2F2015%2F&amp;cb=f3a1840089\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['1297'] = '';
OA_output['1297'] += "<"+"script src=\"http://ad.adip.ly/dlvr/adiply_statmarg.min.js?site_id=SportsReference_AP&t=120\"><"+"/script><"+"div id=\'beacon_ca5584fff8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=1309&amp;campaignid=196&amp;zoneid=1297&amp;OABLOCK=86400&amp;OASCAP=3&amp;loc=1&amp;referer=http%3A%2F%2Fwww.pro-football-reference.com%2Fyears%2F2015%2F&amp;cb=ca5584fff8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
